# -*- coding: utf-8 -*-
"""02_단순선형회귀-당뇨병.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I3BAxDt8w2bU0kmK1X4r6KN0aCTLvN8w

# 단순선형회귀 - 당뇨병사례
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""- 당뇨병 데이터셋 탐색"""

from sklearn.datasets import load_diabetes
dia = load_diabetes()
df = pd.DataFrame(dia.data, columns = dia.feature_names)
df['target'] = dia.target
df.head()

df.describe()

print(dia.DESCR)

"""### 10 개의 feature과 target 간의 상관관계도"""

import seaborn as sns

_, ax = plt.subplots(2, 5, figsize = (18, 8))
for i, feature in enumerate(df.columns[:-1]):
    row, col = i // 5, i % 5
    sns.regplot(x = feature, y = 'target', data = df, ax= ax[row][col])

"""### Feature vs target"""

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

for feature in df.columns[:-1]:
    X = df[[feature]]
    lr.fit(X, dia.target)
    score = lr.score(X, dia.target)
    print(f'{feature} :  {score:.4f}')

"""### BMI vs Target - train/test split"""

from sklearn.model_selection import train_test_split
# 회귀는 stratify 가 없음
X_train, X_test, y_train, y_test = train_test_split(
    df[['bmi']], df.target, test_size = 0.1, random_state = 2022
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

lr = LinearRegression()
lr.fit(X_train, y_train)

# 계수, 절편, 잔차제곱의 합
lr.coef_, lr.intercept_, lr._residues

from sklearn.metrics import r2_score
pred = lr.predict(X_test)
r2_score(y_test, pred)

import seaborn as sns
sns.regplot(X_train, y_train);

